# Generated by Django 4.1 on 2022-10-29 13:34

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_first_name_user_last_name_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to=users.models.avatars_directory_path, verbose_name='Profile Image'),
        ),
    ]
