# Generated by Django 4.1 on 2022-10-27 02:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='started_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Started On'),
            preserve_default=False,
        ),
    ]
